### ISSUE TITLE
Provider message updates crash in compact event emission

### ISSUE THREAD

**Issue by cassi-volkova** [exordos/workspace_backend#98]
## Summary

Provider-backed message updates can crash the inbound Provider event handler after the compact projection optimization. The failed atomic batch is retried, so Zulip-to-Workspace delivery stalls and the bridge outbox grows even though provider polling and Workspace-to-Zulip delivery remain healthy.

## Affected version

- `workspace_backend 0.1.35`
- The regression path was introduced by #93 / commit `71587b1`.

## Reproduction

1. Create or import a provider-backed message.
2. Submit a non-backfill `message.upsert` for the same message with a changed projection.
3. `provider_event_apply._message_event()` calls `helpers.create_compact_workspace_message_updated_events()`.
4. The helper executes `_COMPACT_USER_MESSAGE_SNAPSHOTS_SQL`, receives mapping rows from `fetchall()`, and passes them to `messenger_events.create_message_updated_events(..., compact=True)`.

## Actual result

`create_message_updated_events()` accesses `user_messages[0].uuid`, but the compact SQL result is a mapping, causing:

```text
AttributeError: 'dict' object has no attribute 'uuid'
```

The exception rolls back the atomic Provider event batch. Subsequent inbound records remain pending and are retried.

## Expected result

Compact message-update events should accept the same row shape returned by the compact SQL query (or normalize it before calling the event helper), allowing the Provider batch to commit.

## Notes

The current tests mock `create_compact_workspace_message_updated_events()` at the provider apply boundary, so they do not cover the mapping-to-event integration that fails here. A regression test should exercise the real compact helper with SQL-style mapping rows and confirm that a changed provider message update commits and emits the scoped update event.
